In [1]:
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.utils import to_categorical
import numpy as np
import matplotlib.pyplot as plt

# Step 1: Load and preprocess the MNIST dataset
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

# Normalize the images to [0, 1] range
train_images = train_images / 255.0
test_images = test_images / 255.0

# Convert labels to one-hot encoding
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

# Step 2: Build the model with specified layers
model = Sequential([
    Flatten(input_shape=(28, 28)),  # Flattens the 28x28 image to 784 inputs
    Dense(50, activation='relu'),   # First hidden layer with 50 neurons
    Dense(20, activation='relu'),   # Second hidden layer with 20 neurons
    Dense(10, activation='relu'),   # Third hidden layer with 10 neurons
    Dense(10, activation='softmax') # Output layer with 10 neurons (one for each class)
])

# Compile the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Step 3: Train the model
model.fit(train_images, train_labels, epochs=5, batch_size=32, validation_split=0.1)

# Step 4: Evaluate the model
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"Test accuracy: {test_acc:.4f}")

11490434/11490434 [==============================] - 0s 0us/step
Epoch 1/5
1688/1688 [==============================] - 13s 6ms/step - loss: 0.4046 - accuracy: 0.8800 - val_loss: 0.1816 - val_accuracy: 0.9492
Epoch 2/5
1688/1688 [==============================] - 6s 4ms/step - loss: 0.1649 - accuracy: 0.9521 - val_loss: 0.1207 - val_accuracy: 0.9665
Epoch 3/5
1688/1688 [==============================] - 7s 4ms/step - loss: 0.1260 - accuracy: 0.9621 - val_loss: 0.1099 - val_accuracy: 0.9683
Epoch 4/5
1688/1688 [==============================] - 6s 4ms/step - loss: 0.1013 - accuracy: 0.9693 - val_loss: 0.0988 - val_accuracy: 0.9718
Epoch 5/5
313/313 [==============================] - 1s 2ms/step - loss: 0.1139 - accuracy: 0.9662
Test accuracy: 0.9662


In [2]:
#Save the entire model in model.h5 file
model.save("model.h5")
print("Saved model to disk")

Saved model to disk


/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [3]:
model = tf.keras.models.load_model('model.h5')
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()#saving converted model in "converted_model.tflite" file
open("converted_model.tflite", "wb").write(tflite_model)

165156

In [4]:
mnist_train, _ = tf.keras.datasets.mnist.load_data()
images = tf.cast(mnist_train[0], tf.float32) / 255.0
mnist_ds = tf.data.Dataset.from_tensor_slices((images)).batch(1)
def representative_data_gen():
  for input_value in mnist_ds.take(100):
    yield [input_value]

In [5]:
model = tf.keras.models.load_model('model.h5')
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
converter.representative_dataset = representative_data_gen
tflite_quant_model = converter.convert()#saving converted model in "converted_quant_model.tflite" file
open("converted_quant_model.tflite", "wb").write(tflite_quant_model)

/usr/local/lib/python3.10/dist-packages/tensorflow/lite/python/convert.py:953: UserWarning: Statistics for quantized inputs were expected, but not specified; continuing anyway.
  warnings.warn(


44512

In [8]:
import os
print("Float model in Mb:", os.path.getsize('converted_model.tflite') / float(2**20))
print("Quantized model in Mb:", os.path.getsize('converted_quant_model.tflite') / float(2**20))
print("Compression ratio:", os.path.getsize('converted_model.tflite')/os.path.getsize('converted_quant_model.tflite'))

Float model in Mb: 0.15750503540039062
Quantized model in Mb: 0.042449951171875
Compression ratio: 3.7103702372393963


In [9]:
# Load MNIST test data
(_, _), (test_images, test_labels) = mnist.load_data()
test_images = test_images / 255.0  # Normalize the images

# Load the TFLite model and allocate tensors
interpreter = tf.lite.Interpreter(model_path="converted_quant_model.tflite")
interpreter.allocate_tensors()

# Get input and output tensors
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

In [10]:
# Function to run inference on a single image
def run_inference(image):
    interpreter.set_tensor(input_details[0]['index'], image)
    interpreter.invoke()
    output_data = interpreter.get_tensor(output_details[0]['index'])
    return output_data

In [12]:
# Evaluate accuracy
correct_predictions = 0
for i in range(len(test_images)):
    # Prepare the image for the model based on the model's input shape
    image = np.expand_dims(test_images[i], axis=-1)  # Add channel dimension
    image = np.expand_dims(image, axis=0).astype(np.float32)  # Add batch dimension

    # Check if we need to adjust dimensions to fit the model's expected input
    expected_shape = input_details[0]['shape']
    if len(expected_shape) == 3:  # If model expects (1, height, width)
        image = image.squeeze(axis=-1)  # Remove the channel dimension

    predicted = run_inference(image)
    if np.argmax(predicted) == test_labels[i]:
        correct_predictions += 1

accuracy = correct_predictions / len(test_images)
print(f"Quantized Model Test Accuracy: {accuracy:.4f}")

Quantized Model Test Accuracy: 0.9665


In [17]:
# Path to your quantized TFLite model
tflite_model_path = "converted_quant_model.tflite"

# Load the TFLite model using the Interpreter
interpreter = tf.lite.Interpreter(model_path=tflite_model_path)
interpreter.allocate_tensors()

# Get details for all tensors
tensor_details = interpreter.get_tensor_details()

In [19]:
# Iterate over each tensor
for detail in tensor_details:
    print("Tensor Name:", detail['name'])
    # Identify if the tensor is a weight or bias
    if 'kernel' in detail['name'] or 'bias' in detail['name']:
        # Retrieve the tensor data (weights/biases) using the tensor index
        tensor = interpreter.get_tensor(detail['index'])

        # Print the layer name and tensor details
        print(f"Layer: {detail['name']}")
        print("Shape:", detail['shape'])

        # Check if the tensor has quantization parameters
        if detail['quantization_parameters']:
            print("Quantized Scale:", detail['quantization_parameters']['scales'])
            print("Quantized Zero Point:", detail['quantization_parameters']['zero_points'])

        print("Tensor Values:")
        print(tensor)
        print("\n")

Tensor Name: serving_default_flatten_input:0
Tensor Name: sequential/flatten/Const
Tensor Name: sequential/dense_3/BiasAdd/ReadVariableOp
Tensor Name: sequential/dense_3/MatMul
Tensor Name: sequential/dense_2/BiasAdd/ReadVariableOp
Tensor Name: sequential/dense_2/MatMul
Tensor Name: sequential/dense_1/BiasAdd/ReadVariableOp
Tensor Name: sequential/dense_1/MatMul
Tensor Name: sequential/dense/BiasAdd/ReadVariableOp
Tensor Name: sequential/dense/MatMul
Tensor Name: tfl.quantize
Tensor Name: sequential/flatten/Reshape
Tensor Name: sequential/dense/MatMul;sequential/dense/Relu;sequential/dense/BiasAdd
Tensor Name: sequential/dense_1/MatMul;sequential/dense_1/Relu;sequential/dense_1/BiasAdd
Tensor Name: sequential/dense_2/MatMul;sequential/dense_2/Relu;sequential/dense_2/BiasAdd
Tensor Name: sequential/dense_3/MatMul;sequential/dense_3/BiasAdd
Tensor Name: StatefulPartitionedCall:01
Tensor Name: StatefulPartitionedCall:0


In [20]:
# Iterate over each tensor
for detail in tensor_details:
    # Identify if the tensor is likely a weight or bias
    if 'MatMul' in detail['name'] or 'BiasAdd' in detail['name']:
        # Retrieve the tensor data using the tensor index
        tensor = interpreter.get_tensor(detail['index'])

        # Print the layer name and tensor details
        print(f"Layer: {detail['name']}")
        print("Shape:", detail['shape'])

        # Check if the tensor has quantization parameters
        if detail['quantization_parameters']:
            print("Quantized Scale:", detail['quantization_parameters']['scales'])
            print("Quantized Zero Point:", detail['quantization_parameters']['zero_points'])

        print("Tensor Values:")
        print(tensor)
        print("\n")

Layer: sequential/dense_3/BiasAdd/ReadVariableOp
Shape: [10]
Quantized Scale: [0.00079298]
Quantized Zero Point: [0]
Tensor Values:
[-135  216 -144  -20   82 -159 -312  124  312  -12]


Layer: sequential/dense_3/MatMul
Shape: [10 10]
Quantized Scale: [0.00709861]
Quantized Zero Point: [0]
Tensor Values:
[[ -17   56 -106   95  -74   16   -8   55  -54  -17]
 [ -32  -76   16   48  -12    5  -83  -36  108  -91]
 [  19   21  -71  -43   45  -70 -108  -77    4   48]
 [  58   38  -19  -47  -66  -52   57  -34   12  -84]
 [ -10  -24   24  -28 -110   30    0  -42  -60   77]
 [-119   -7  -39  -28   50  -27   69   -1   27   -9]
 [   3  -39 -114   90 -127  -18   15   76   32   19]
 [  26  -28  -49   34   73   93  -19  -72  -53  -76]
 [ -90   43  -38  -18  -90   42  -71   -4   62   -9]
 [-121   16   91  -16   38  -12   21    5  -53  -23]]


Layer: sequential/dense_2/BiasAdd/ReadVariableOp
Shape: [10]
Quantized Scale: [0.00065755]
Quantized Zero Point: [0]
Tensor Values:
[-103   55  328  -93  -38  234

ValueError: Tensor data is null. Run allocate_tensors() first

In [27]:
# Path to your quantized TFLite model
tflite_model_path = "converted_quant_model.tflite"

# Load the TFLite model using the Interpreter
interpreter = tf.lite.Interpreter(model_path=tflite_model_path)
interpreter.allocate_tensors()  # Ensure tensors are allocated

# Get details for all tensors
tensor_details = interpreter.get_tensor_details()

# Open a file to write the weights and biases
with open("model_weights_and_biases.txt", "w") as file:
    # Iterate over each tensor
    for detail in tensor_details:
        # Identify if the tensor is likely a weight or bias
        if 'MatMul' in detail['name'] or 'BiasAdd' in detail['name']:
            # Retrieve the tensor data using the tensor index
            tensor = interpreter.get_tensor(detail['index'])

            # Write the layer name and tensor details to the file
            file.write(f"Layer: {detail['name']}\n")
            file.write("Shape: {}\n".format(detail['shape']))

            # Check if the tensor has quantization parameters
            if detail['quantization_parameters']:
                file.write("Quantized Scale: {}\n".format(detail['quantization_parameters']['scales']))
                file.write("Quantized Zero Point: {}\n".format(detail['quantization_parameters']['zero_points']))

            file.write("Tensor Values:\n")
            file.write("{}\n\n".format(tensor))


ValueError: Tensor data is null. Run allocate_tensors() first

In [28]:
# Path to your quantized TFLite model
tflite_model_path = "converted_quant_model.tflite"

# Load the TFLite model using the Interpreter
interpreter = tf.lite.Interpreter(model_path=tflite_model_path)
interpreter.allocate_tensors()  # Ensure tensors are allocated

# Get details for all tensors
tensor_details = interpreter.get_tensor_details()

# Prepare to display full arrays without truncation
np.set_printoptions(threshold=np.inf, linewidth=np.inf)  # Avoid truncation

# Extract and print the 'sequential/dense/MatMul' layer specifically
for detail in tensor_details:
    if detail['name'] == 'sequential/dense/MatMul':
        # Access the tensor data
        interpreter.allocate_tensors()  # Ensure valid state
        tensor = interpreter.tensor(detail['index'])()  # Get tensor data

        # Prepare the display content
        content = [
            f"Layer: {detail['name']}",
            f"Shape: {detail['shape']}",
            f"Quantized Scale: {detail['quantization_parameters']['scales']}",
            f"Quantized Zero Point: {detail['quantization_parameters']['zero_points']}",
            "Tensor Values:",
            f"{tensor}"
        ]

        # Combine all parts into a single output
        full_details = "\n".join(content)

        # Print or save this information as needed
        print(full_details)
        break  # Since we're only interested in this specific layer, we can stop after finding it

Layer: sequential/dense/MatMul
Shape: [ 50 784]
Quantized Scale: [0.00692134]
Quantized Zero Point: [0]
Tensor Values:
[[  -1    1    0   -1    7    3    9    1    1    8   10    8   -8    4   18   -5   -1   10   -3   -7    0   -7    9  -10  -12   -7   10   11   -7    3   10    3    3    4   20   32   34    5   12   13    8    7   29   33   26    7    8   21   18   -8   19   20   -1    3    2  -11    0  -10    2    9    4   16   23   33   28   13   19    5    6   44   23   44   30   45   50   28   20   -5  -10    9    2   20    7   -4   -4   11   -9   18  -12  -11   -4    3  -15   16  -12  -28  -16    7    4   29    5  -12    3   14   25   12   13   -6    6    5   -6    6   -2  -13   -9   -9   -1   17   24   11   -3  -19    9    1  -13  -12   13    3    9    0   14   18   -4    4   -6   25   33   11    5    7   -6    6   -3  -28  -10   -2   -1  -25  -20    7   21   11   -9    2   12   12   22   33   32    7   17   19    2   26   12   -6   12    5   12  -11  -17  -15    1   -8    3  -10

In [29]:

# Path to your quantized TFLite model
tflite_model_path = "converted_quant_model.tflite"

# Load the TFLite model using the Interpreter
interpreter = tf.lite.Interpreter(model_path=tflite_model_path)
interpreter.allocate_tensors()  # Ensure tensors are allocated

# Get details for all tensors
tensor_details = interpreter.get_tensor_details()

# Prepare to display full arrays without truncation
np.set_printoptions(threshold=np.inf, linewidth=np.inf)  # Avoid truncation

# Open a file to write the specific layer's weights and biases
with open("specific_layer_weights_and_biases.txt", "w") as file:
    # Extract and write the 'sequential/dense/MatMul' layer specifically
    for detail in tensor_details:
        if detail['name'] == 'sequential/dense/MatMul':
            # Access the tensor data
            interpreter.allocate_tensors()  # Ensure valid state
            tensor = interpreter.tensor(detail['index'])()  # Get tensor data

            # Write the layer details to the file
            file.write(f"Layer: {detail['name']}\n")
            file.write(f"Shape: {detail['shape']}\n")
            file.write(f"Quantized Scale: {detail['quantization_parameters']['scales']}\n")
            file.write(f"Quantized Zero Point: {detail['quantization_parameters']['zero_points']}\n")
            file.write("Tensor Values:\n")
            file.write(f"{tensor}\n\n")

            print("Saved specific layer details to specific_layer_weights_and_biases.txt")
            break  # Since only this layer's details are needed, stop after processing it

Saved specific layer details to specific_layer_weights_and_biases.txt
